OverTheTop2/Controllers/CategoryController.cs
using OverTheTop2.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OverTheTop2.ViewModels;

namespace OverTheTop2.Controllers
{
    public class CategoryController : Controller
    {
        private ApplicationDbContext _context;

        public CategoryController()
        {
            _context = new ApplicationDbContext();
        }

    

        [Authorize(Roles = "Admin")]
        public ActionResult New()
        {
            

            return View("CategoryForm");
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Save(Category category)
        {
            if (category.id == 0)
            {
                _context.Categories.Add(category);

            }
            else
            {
                var categoryInDb = _context.Categories.Single(c => c.id == category.id);
                categoryInDb.Name = category.Name;
                categoryInDb.Description = category.Description;
            }

            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var category = _context.Categories.SingleOrDefault(c => c.id == id);
            if (category == null)
            {
                return HttpNotFound();
            }

            return View("CategoryForm", category);
        }
    }
}

OverTheTop2/Controllers/HomeController.cs
using OverTheTop2.Models;
using System;
using System.CodeDom;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Net.Mime;
using OverTheTop2.ViewModels;

namespace OverTheTop2.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext _context;

        public HomeController()
        {
            _context =new ApplicationDbContext();
        }

        public ActionResult SiteMap()
        {
            string xml = System.IO.File.ReadAllText(Server.MapPath("~/web.sitemap"));
            return Content(xml,MediaTypeNames.Text.Xml);
        }

        public ActionResult Index()
        {

            var categories = _context.Categories.Include(c => c.SubCategory).Include(c => c.CategoryImages).ToList();
            var reviews = _context.Reviews;

            IndexFormViewModel viewModel = new IndexFormViewModel
            {
                Categories = categories,
                Reviews = reviews
            };

            if (User.IsInRole("Admin"))
            {
                return View("Index_Admin", viewModel);
            }
            else
            {
                return View("Index", viewModel);
            }

        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

OverTheTop2/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OverTheTop2.Models;

namespace OverTheTop2.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ReviewsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Reviews

        public ActionResult Index()
        {
            return View(db.Reviews.ToList());
        }

        // GET: Reviews/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        // GET: Reviews/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,ReviewDate")] Review review)
        {
            if (ModelState.IsValid)
            {
                db.Reviews.Add(review);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(review);
        }

        // GET: Reviews/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,ReviewDate")] Review review)
        {
            if (ModelState.IsValid)
            {
                db.Entry(review).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(review);
        }

        // GET: Reviews/Delete/5
        public ActionResult Delete(int id)
        {        
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            db.Reviews.Remove(review);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
     
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OverTheTop2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

OverTheTop2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<div class="row card shadow">
    <div class="col-md-12">
        <h1>Owner</h1>
        <h3>John Vangeemen</h3>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Email: <a href="mailto:fixitonce@hotmail.ca">fixitonce@hotmail.ca</a></li>
            <li class="list-group-item">Phone: 289-213-3880</li>
        </ul>
    </div>
</div>

<div class="row card shadow">
    <div class="col-md-12">
        <h1>Webmaster / Developer</h1>
        <h3>John Vangeemen JR</h3>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Email: <a href="mailto:john@johnvangeemen.com">john@johnvangeemen.com</a></li>
            <li class="list-group-item">Phone: 905-931-3555</li>
            <li class="list-group-item">Portfolio: <a href="https://www.johnvangeemen.com">www.johnvangeemen.com</a></li>
        </ul>
    </div>
</div>

OverTheTop2/Views/Home/Index.cshtml
@model OverTheTop2.ViewModels.IndexFormViewModel
@{
    ViewBag.Title = "Home Page";
}

<div class="row mission-card">
    <div class="col-lg-12 ">

        <h3>&emsp; Our obligation to you is to enhance the structural integrity of your boat's transom, stringer, and floors with custom solutions that deliver satisfaction. We design and build cabinets, benches, and stairs that beautify your boat interior while optimizing space and function. We obsess over details and work meticulously, treating every boat like it's our own.</h3>
        <p class="text-right">- John Van Geemen</p>
    </div>
</div>

@if (Model.Reviews.Count() != 0)
{
    <div class="row card shadow">
        <h1>Testimonials</h1>

        @foreach (var review in Model.Reviews)
        {
            <div class="row testimonials-card">
                <div cass="col-md-12">
                    <h4>&emsp; @review.Description</h4>
                    <p class="text-right">- @review.Name | @review.ReviewDate.ToString("dddd, dd MMMM yyyy") </p>
                </div>
            </div>
        }
    </div>
}

<div class="row ">
    @foreach (var category in Model.Categories)
    {

        <div class="col-lg-6">
            <div class="card shadow">

                <div class="row">
                    <div class="col-lg-12">
                        <h1><a runat="server" href="#">@category.Name</a></h1>
                        <h5 class="well">&emsp; @category.Description</h5>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <ul class="list-group">
                            @foreach (var sub in category.SubCategory)
                            {
                                @Html.ActionLink(sub.Name, "Details", "SubCategories", new { id = sub.Id }, new { @class = "list-group-item" })
                            }
                        </ul>

                    </div>
                </div>
                <div class="row">



                    <div class="col-lg-12">
                        <div id="@category.id" class="carousel slide" data-ride="carousel">

                            <ol class="carousel-indicators">
                                @for (var i = 0; i < category.CategoryImages.Count(); i++)
                                {
                                    var active = "";
                                    if (i == 0)
                                    {
                                        active = "active";

                                    }
                                    else
                                    {
                                        active = "";
                                    }
                                    <li data-target="#@category.id;" data-slide-to="@i" class="@active"></li>
                                }
                            </ol>


                            <div class="carousel-inner">
                                @{
                                    var im = 0;
                                }
                                @foreach (var img in category.CategoryImages)
                                {
                                    var active = "";
                                    if (im == 0)
                                    {
                                        active = "item active";

                                    }
                                    else
                                    {
                                        active = "item";
                                    }
                                    <div class="@active">
                                        <img src="@Url.Content(img.Image)" value="@img.Image" />
                                    </div>
                                    im++;
                                }
                            </div>


                            <a class="left carousel-control" href="#@category.id" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#@category.id" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>

                </div>
            </div>
        </div>


    }
</div>

OverTheTop2/Views/Home/Index_Admin.cshtml
@model OverTheTop2.ViewModels.IndexFormViewModel
@{
    ViewBag.Title = "Home Page";
}

<div class="row mission-card">
    <div class="col-lg-12 ">

        <h3>&emsp; Our obligation to you is to enhance the structural integrity of your boat's transom, stringer, and floors with custom solutions that deliver satisfaction. We design and build cabinets, benches, and stairs that beautify your boat interior while optimizing space and function. We obsess over details and work meticulously, treating every boat like it's our own.</h3>
        <p class="text-right">- John Van Geemen</p>
    </div>
</div>
@Html.ActionLink("Testimonials", "index", "Reviews", null, new { @class = "btn btn-primary" })
@if (Model.Reviews.Count() != 0)
{
    <div class="row card shadow ">
        <h1>Testimonials</h1>

        @foreach (var review in Model.Reviews)
        {
            <div class="row testimonials-card">
                <div cass="col-md-12">
                    <h4>&emsp; @review.Description</h4>
                    <p class="text-right">- @review.Name | @review.ReviewDate.ToString("dddd, dd MMMM yyyy") </p>
                </div>
            </div>
        }
    </div>
}

<div class="row ">
    @foreach (var category in Model.Categories)
    {

        <div class="col-lg-6">
            <div class="card shadow">

                <div class="row">
                    <div class="col-lg-12">
                        @Html.ActionLink("Edit Title and Description", "Edit", "Category", new { id = category.id }, new { @class = "btn btn-primary" })
                        <h1><a runat="server" href="#">@category.Name</a></h1>
                        <h5 class="well">&emsp; @category.Description</h5>

                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        @Html.ActionLink("Add SubCategory", "New", "SubCategories", new { id = category.id }, new { @class = "btn btn-primary" })
                        <ul class="list-group">
                            @foreach (var sub in category.SubCategory)
                            {
                                @Html.ActionLink(sub.Name, "Details", "SubCategories", new { id = sub.Id }, new { @class = "list-group-item" })
                            }
                        </ul>

                    </div>
                </div>
                <div class="row">



                    <div class="col-lg-12">
                        @Html.ActionLink("Add/ Remove images", "Index", "CategoryImages", new { id = category.id }, new { @class = "btn btn-primary" })
                        <div id="@category.id" class="carousel slide" data-ride="carousel">

                            <ol class="carousel-indicators">
                                @for (var i = 0; i < category.CategoryImages.Count(); i++)
                                {
                                    var active = "";
                                    if (i == 0)
                                    {
                                        active = "active";

                                    }
                                    else
                                    {
                                        active = "";
                                    }
                                    <li data-target="#@category.id" data-slide-to="@i" class="@active"></li>
                                }
                            </ol>


                            <div class="carousel-inner">
                                @{
                                    var im = 0;
                                }
                                @foreach (var img in category.CategoryImages)
                                {
                                    var active = "";
                                    if (im == 0)
                                    {
                                        active = "item active";

                                    }
                                    else
                                    {
                                        active = "item";
                                    }
                                    <div class="@active">
                                        <img src="@Url.Content(img.Image)" value="@img.Image" />
                                    </div>
                                    im++;
                                }
                            </div>


                            <a class="left carousel-control" href="#@category.id" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#@category.id" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>

                </div>
            </div>
        </div>


    }
</div>