OverTheTop2/Models/SubCategoryImage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OverTheTop2.Models
{
    public class SubCategoryImage
    {
        public int id { get; set; }
        public string directory { get; set; }    
    }
}

OverTheTop2/Controllers/SubCategoryImagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OverTheTop2.Models;

namespace OverTheTop2.Controllers
{
    public class SubCategoryImagesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize(Roles = "Admin")]
        public ActionResult Add(int id)
        {
            var subCat = db.SubCategories.Single(i => i.Id == id);

            return View(subCat);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Upload(IEnumerable<HttpPostedFileBase> Images, int id)
        {
            SubCategory Subcategory = db.SubCategories.Include(i => i.SubCategoryImages).Single(i => i.Id == id);


            foreach (var file in Images)
            {
                var guid = Guid.NewGuid();
                if (file != null && file.ContentLength > 0)
                {

                    var path = Server.MapPath("~/Images/SubCategoryImages") + "/" +guid+ file.FileName;

                    file.SaveAs(path);


                    SubCategoryImage newImg = new SubCategoryImage()
                    {
                        directory = "~/Images/SubCategoryImages/"  +guid+ file.FileName
                    };

                    Subcategory.SubCategoryImages.Add(newImg);



                    //handle files;
                }
            }

            db.SaveChanges();
            return RedirectToAction("Details", "SubCategories", new { id = id });
        }





        // GET: SubCategoryImages/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id, int subCAt)
        {
            SubCategoryImage subCategoryImage = db.SubCategoryImages.Find(id);
            if (subCategoryImage == null)
            {
                return HttpNotFound();
            }

            db.SubCategoryImages.Remove(subCategoryImage);
            db.SaveChanges();
            return RedirectToAction("Details", "SubCategories", new{id = subCAt });
        }

     

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OverTheTop2/Views/SubCategoryImages/Add.cshtml
@model OverTheTop2.Models.SubCategory

@{
    ViewBag.Title = "Create";
}
<div class="card shadow">
    <h2>@Model.Name</h2>

    @using (Html.BeginForm("Upload", "SubCategoryImages", new { id = Model.Id }, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input type="file" name="Images" multiple />
        <button class="btn btn-default">Upload</button>
    }

</div>

OverTheTop2/Views/SubCategoryImages/Edit.cshtml
@model OverTheTop2.Models.SubCategory

@{
    ViewBag.Title = "Index";
}

<div class="row card shadow">
    <p>
        @Html.ActionLink("Add New Image", "Create",new {id = Model.Id }, new {@class ="btn btn-default"})
    </p>


         
    @{ var imgs = Model.SubCategoryImages.ToList();}
    <div class="row">
        @for (int i = 0; i < Model.SubCategoryImages.Count; i++)
        {
            if (i > 0 && i % 4 == 0)
            {
                @:</div><div class="row">
            }

            <div class="col-md-3 card">
                        
                <img src="@Url.Content(imgs[i].directory)" class="squareImg" />
                       
                        
                @Html.ActionLink("Delete", "Delete", new {imgId = imgs[i].id, catId = Model.Id}, new {@class = "btn btn-danger deleteImg", @onclick = "return confirm('Are you sure you want to delete?');"})
            </div>
        }
    </div>               
</div>